// AUTO-GENERATED by `env-manager ts` - do not edit
import { z } from 'zod';

const env = z.object({
  COOKUNITY_ACCESS_TOKEN: z.string().optional(),
  WHOOP_CLIENT_ID: z.string(),
  WHOOP_CLIENT_SECRET: z.string(),
  WHOOP_REFRESH_TOKEN: z.string().optional(),
  WHOOP_REDIRECT_URI: z.string(),
  GEMINI_API_KEY: z.string(),
  GOOGLE_MAPS_API_KEY: z.string(),
  MACROFACTOR_CREDENTIALS: z.string(),
  AI_COMITTER_NAME: z.string().optional(),
  AI_COMMITTER_NAME: z.string().optional(),
  DEFAULT_AI_COMITTER_NAME: z.string().optional(),
  DEFAULT_AI_COMMITTER_NAME: z.string().optional(),
  AI_COMITTER_EMAIL: z.string().optional(),
  AI_COMMITTER_EMAIL: z.string().optional(),
  DEFAULT_AI_COMITTER_EMAIL: z.string().optional(),
  DEFAULT_AI_COMMITTER_EMAIL: z.string().optional(),
  ANYLIST_CREDENTIALS: z.string().regex(/.+@.+:.+/).optional(),
  EMAIL_INBOX_URL: z.url(),
  EMAIL_INBOX_TOKEN: z.string(),
  SMS_INBOX_URL: z.url(),
  SMS_INBOX_TOKEN: z.string(),
}).parse(process.env);

export default env;
