// AUTO-GENERATED by `env-manager ts` - do not edit
import { ZodError, z } from 'zod';

const envSchema = z.object({
  WHOOP_CLIENT_ID: z.string(),
  WHOOP_CLIENT_SECRET: z.string(),
  WHOOP_REFRESH_TOKEN: z.string().optional(),
  WHOOP_REDIRECT_URI: z.string().optional(),
  GEMINI_API_KEY: z.string(),
  MACROFACTOR_CREDENTIALS: z.string().optional(),
  AI_COMITTER_NAME: z.string().optional(),
  AI_COMMITTER_NAME: z.string().optional(),
  DEFAULT_AI_COMITTER_NAME: z.string().optional(),
  DEFAULT_AI_COMMITTER_NAME: z.string().optional(),
  AI_COMITTER_EMAIL: z.string().optional(),
  AI_COMMITTER_EMAIL: z.string().optional(),
  DEFAULT_AI_COMITTER_EMAIL: z.string().optional(),
  DEFAULT_AI_COMMITTER_EMAIL: z.string().optional(),
});

type Env = z.infer<typeof envSchema>;

let cachedEnv: Env | null = null;
const envShape = envSchema.shape;

function runtimeEnv(): Record<string, string | undefined> {
  return process.env as Record<string, string | undefined>;
}

export function readEnv(): Env {
  if (cachedEnv === null) {
    cachedEnv = envSchema.parse(runtimeEnv());
  }
  return cachedEnv;
}

export function getEnvVar(name: string): string | undefined {
  return runtimeEnv()[name];
}

export function setEnvVarIfUnset(name: string, value: string): void {
  if (runtimeEnv()[name] === undefined) {
    runtimeEnv()[name] = value;
    cachedEnv = null;
  }
}

function readEnvValue<Key extends keyof Env>(name: Key): Env[Key] {
  try {
    const parser = envShape[name] as z.ZodType<Env[Key]>;
    return parser.parse(runtimeEnv()[name]);
  } catch (error) {
    if (error instanceof ZodError) {
      throw new Error(`${String(name)}: ${error.message}`);
    }
    throw error;
  }
}

const env = new Proxy({} as Env, {
  get(_target, property) {
    if (typeof property !== 'string') {
      return undefined;
    }
    return readEnvValue(property as keyof Env);
  },
}) as Env;

export default env;
