// AUTO-GENERATED by `env-manager ts` - do not edit
import { z } from 'zod';

const env = z.object({
  WHOOP_CLIENT_ID: z.string(),
  WHOOP_CLIENT_SECRET: z.string(),
  WHOOP_REFRESH_TOKEN: z.string().optional(),
  WHOOP_REDIRECT_URI: z.string(),
  GEMINI_API_KEY: z.string(),
  MACROFACTOR_CREDENTIALS: z.string(),
  MACROFACTOR_FIREBASE_REFRESH_TOKEN: z.string().optional(),
  MACROFACTOR_FIREBASE_APP_CHECK_TOKEN: z.string().optional(),
  ERA_FIT_CREDENTIALS: z.string().optional(),
  ERA_FIT_SESSION_COOKIE: z.string().optional(),
  ERA_FIT_FIREBASE_ID_TOKEN: z.string().optional(),
  AI_COMITTER_NAME: z.string().optional(),
  AI_COMMITTER_NAME: z.string().optional(),
  DEFAULT_AI_COMITTER_NAME: z.string().optional(),
  DEFAULT_AI_COMMITTER_NAME: z.string().optional(),
  AI_COMITTER_EMAIL: z.string().optional(),
  AI_COMMITTER_EMAIL: z.string().optional(),
  DEFAULT_AI_COMITTER_EMAIL: z.string().optional(),
  DEFAULT_AI_COMMITTER_EMAIL: z.string().optional(),
  ANYLIST_CREDENTIALS: z.string().regex(/.+@.+:.+/).optional(),
  ERA_FIT_FIREBASE_API_KEY: z.string().optional(),
}).parse(process.env);

export default env;
